backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

logo_url: https://www.gelagency.com/img/Gel_Written_Whimsical_Colour_550x350_Transparent_Background.gif

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image (for blog list page)", name: "featured_image", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}
      - {label: "Banner Image", name: "banner_image", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "portfolio-entry"
    label: "Portfolio Entries"
    folder: "src/pages/portfolio-entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-entry"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date (Projects will be sorted based on date, in descending order)", name: "date", widget: "datetime"}
      - {label: "Project Type (e.g. Visual Identity)", name: "project_type", widget: "string"}
      - {label: "Home Page Featured Image", name: "home_page_featured", required: false, widget: "object", fields: [{label: "Featured Image", name: "featured_image", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}, {label: "Is Featured?", name: "is_featured", widget: "boolean"}]}
      - {label: "Grid Image (for grid on portfolio page)", name: "colour_grid_image", required: false, widget: "image"}
      - {label: "Header Image", name: "header_image", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}
      - {label: "Project Intro", name: "project_intro", widtet: text}
      - {label: "Project Image Section 1", name: "project_images_1", widget: list, fields: [{label: "Image", name: "image", widget: "image"}]}
      - {label: "Main", name: "main", widget: "object", fields: [{label: "Detail Text", name: "detail_text", widget: "text"}, {label: "Image", name: "image", widget: "image"}]}
      - {label: "Project Image Section 2", name: "project_images_2", widget: list, fields: [{label: "Image", name: "image", widget: "image"}]}
  - name: "client-logo"
    identifier_field: "clientName"
    extension: "yml"
    label: "Client Logos"
    label_singular: "Client Logo"
    folder: "src/client-logos"
    create: true
    fields:
      - {label: "Client Name", name: "clientName", widget: "string"}
      - {label: "Publish Date (Logos will be displayed according to date in descending order)", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "object", fields: [{label: "Image (400x200)", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Intro2", name: "intro2", widget: "text"}
          - {label: "Featured Portfolio Pieces Title", name: "featuredPortfolioTitle", widget: "string"}
          - {label: "Client List Title", name: "clientListTitle", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "about_intro", widget: "text"}
          - {label: "Main", name: "main", widget: "object", fields: [{label: "Tom", name: "tom", widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Tom Bio, name: tom_bio, widget: text}]}, {label: "Shannon", name: "shannon", widget: object, fields: [{label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Shannon Bio, name: shannon_bio, widget: text}]}]}
          - {label: "Approach", name: "approach", widget: "object", fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: markdown}]}
          - {label: "Services", name: "services", widget: "list", required: true}
      - file: "src/pages/portfolio/index.md"
        label: "Portfolio Page"
        name: "portfolio"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio"}
          - {label: Title, name: title, widget: string}
          - {label: "Intro", name: "portfolio_intro", widget: string, required: false}